### PR TITLE
Fix for issue 115

### PR DESCRIPTION
**Pull request by Madu86**
The issue #115 is caused by missing case conversion. In other words, If someone put atom labels as "Li" instead of "LI" QUICK is doomed. Another potential hazard is hardcoded 80s in read statements:`read (input,'(A80)')`. If someone exceeds 80 characters, we are in trouble again. We unarguably have the dumbest IO system on earth!

### CODE REVIEW

**Comment by vwcruzeiro** [comment]
@Madu86, I see you are converting the full string to uppercase. This is good, because it makes the input case insensitive. The limit of 80 characters applies to what?

**Comment by Madu86** [comment]
@vwcruzeiro Only for coordinate/point charge blocks. For job keyword, I increased this to 200 sometime ago: https://github.com/merzlab/QUICK/blob/master/src/read_job_and_atom.f90#L40.

**Comment by vwcruzeiro** [comment]
Should we increase 80 to a higher number?

**Comment by Madu86** [comment]
For the time being, I think we are safe. Hopefully people won't use 12 digits for each floating point number and separate columns by 12 characters.

**Comment by vwcruzeiro** [comment]
Ok, ok. Let me merge this PR then.

**Pull request merged**
