### PR TITLE
Fix for issue 102

### PR DESCRIPTION
**Pull request by Madu86**
GPU uploading for geometry optimization should be only performed inside optimization.f90 (https://github.com/Madu86/QUICK/blob/bugfix102/src/optimize.f90#L130-L144). But somehow this also happens also in main.f90 even if Schwarz cutoff and cutoff matrix is not computed there: https://github.com/Madu86/QUICK/blob/bugfix102/src/main.f90#L176-L202. I have eliminated the latter. This fixes the issue #102.

### CODE REVIEW

**Comment by Madu86** [comment]
I don't see why someone would put the cutoff calculation and GPU uploading in two different places. We can simply do these tasks inside scf_operator subroutine. Anyway, lets leave it like this for now. I will make this change during the next code refactoring.

**Review by agoetz — APPROVED** [review]
Looks good.

**Comment by agoetz** [comment]
I am going to merge this as it should be independent of any other open PRs.

**Comment by vwcruzeiro** [comment]
@agoetz Did you test this PR with CUDA and CUDA+MPI?

**Comment by agoetz** [comment]
I did not test it. I looked at the changes in the source code.

**Comment by vwcruzeiro** [comment]
I just tested. All is good.

**Pull request merged**
