### PR TITLE
SAD guess files

### PR DESCRIPTION
**Pull request by agoetz**
Add SAD guess files for all elements of all supported basis sets.
Also activate reading of SAD guess by default.

This has been tested locally. All short tests pass.

### CODE REVIEW

**Comment by agoetz** [comment]
@Madu86 Please take a look and merge this PR if all CI tests pass.

Some basis sets still have transition metals with f functions (first row transition metals as far as I recall) for which no SAD guess was generated: def2-SVP, def2-SVPD, cc-pVDZ. We can add the SAD guess later if we enable f functions.

**Comment by Madu86** [comment]
@agoetz some CI tests failed. But looks like this is due to that indentation issue in SCF. Fixing this.

**Comment by Madu86** [comment]
@agoetz After fixing the indentation, most gradient tests are expected to fail since the reference output files still have the wrong indentation. I am fixing this.

**Comment by Madu86** [comment]
@agoetz So the only failing test is CaCl2 energy calculation at HF/STO-3G level of theory. I dumped CA and CL sad guesses from this calculation. See below for comparison with your's. I see significant differences.

```
[mmanathunga@psgcluster runs]$ diff -y CA ../../pr161/basis/STO-3G.SAD/CA
           1           1   2.3239926292132989     	      |	           1           1   2.3239926292133397     
           1           2 -0.90980396009062325     	      |	           1           2 -0.90980396009059850     
           1           3  -5.2027056325528672E-014	      |	           1           3   8.6841866318777266E-015
           1           4  -1.0821447293505915E-013	      |	           1           4   1.6121357493452602E-015
           1           5  -4.6588896594420319E-015	      |	           1           5   9.2152086334221784E-015
           1           6  0.24361275681104622     	      |	           1           6  0.24361275681105393     
           1           7  -8.9508933939923236E-014	      |	           1           7  -3.3515006236851547E-015
           1           8  -9.1304263381301632E-014	      |	           1           8  -1.8910301095544141E-015
           1           9  -2.1061027080447968E-014	      |	           1           9  -4.3780965221476420E-015
           1          10  -7.1906817042555360E-002	      |	           1          10  -7.1906817042565158E-002
           1          11  -1.0870995490376750E-014	      |	           1          11  -9.2927843873765874E-017
           1          12  -1.2873031950578005E-013	      |	           1          12  -7.9237455633652341E-016
           1          13  -1.3915814446704385E-014	      |	           1          13   1.6202463691374136E-015
           2           1 -0.90980396009062325     	      |	           2           1 -0.90980396009059850     
           2           2   2.5615038040694866     	      |	           2           2   2.5615038040694893     
           2           3  -1.0101573636901153E-013	      |	           2           3  -2.4568932306414237E-014
           2           4  -3.0366419363588107E-014	      |	           2           4  -3.6538285328517605E-016
           2           5  -9.4054471604299879E-015	      |	           2           5  -1.8339535591222448E-014
           2           6 -0.80863439374678936     	      |	           2           6 -0.80863439374679325     
           2           7  -8.3490717186892391E-014	      |	           2           7   5.9234257184585872E-015
           2           8  -2.3241997395987533E-013	      |	           2           8   5.7885360125974010E-015
           2           9  -2.0166801164026711E-014	      |	           2           9   6.7110765413328744E-015
           2          10  0.24552878676617224     	      |	           2          10  0.24552878676616285     
           2          11  -1.8310463861907492E-014	      |	           2          11   4.7597009306442267E-015
           2          12  -7.0579433183959746E-014	      |	           2          12   9.0125550835970554E-017
           2          13  -1.4770284062557133E-014	      |	           2          13  -3.0807416892274513E-015
           3           1  -5.2027056325528672E-014	      |	           3           1   8.6841866318777266E-015
           3           2  -1.0101573636901153E-013	      |	           3           2  -2.4568932306414237E-014
           3           3   2.1814249929681733     	      |	           3           3   2.2039997006752152     
           3           4  -2.2312880709751026E-015	      |	           3           4  -3.3063829452117939E-015
           3           5   5.5025428657984337E-015	      |	           3           5  -6.0173220572945521E-017
           3           6  -5.1125029116304588E-014	      |	           3           6   3.0629360029081160E-015
           3           7 -0.60064611094319265     	      |	           3           7 -0.67013435561129375     
           3           8   1.9255430583318755E-016	      |	           3           8   3.6776137690708295E-015
           3           9  -1.3711254354120685E-014	      |	           3           9   2.0309275094998473E-015
           3          10  -1.0835522103795586E-014	      |	           3          10  -1.3194751679725904E-015
           3          11  -9.8782982032475375E-002	      |	           3          11  -1.4049553848003889E-003
           3          12   8.5541383004769344E-015	      |	           3          12   5.6985666185838409E-016
           3          13  -8.4984103088103590E-015	      |	           3          13  -2.9382014399628731E-015
           4           1  -1.0821447293505915E-013	      |	           4           1   1.6121357493452602E-015
           4           2  -3.0366419363588107E-014	      |	           4           2  -3.6538285328517605E-016
           4           3  -2.2312880709751026E-015	      |	           4           3  -3.3063829452117939E-015
           4           4   2.1814249929681622     	      |	           4           4   2.2039997006752134     
           4           5   2.1710064301849792E-015	      |	           4           5  -1.5178830414796963E-017
           4           6  -1.4773448557886046E-013	      |	           4           6   4.3356075736519431E-015
           4           7  -4.7618159415565926E-015	      |	           4           7   3.9690473130349331E-015
           4           8 -0.60064611094316334     	      |	           4           8 -0.67013435561129042     
           4           9  -5.4522358849951102E-015	      |	           4           9  -1.8526846723432304E-015
           4          10  -3.2621996897293116E-014	      |	           4          10   4.5001602468251434E-015
           4          11  -7.8600320696499095E-015	      |	           4          11  -5.1629707453759674E-015
           4          12  -9.8782982032508432E-002	      |	           4          12  -1.4049553847991399E-003
           4          13   9.6717338998742350E-015	      |	           4          13  -2.3200842289017298E-015
           5           1  -4.6588896594420319E-015	      |	           5           1   9.2152086334221784E-015
           5           2  -9.4054471604299879E-015	      |	           5           2  -1.8339535591222448E-014
           5           3   5.5025428657984337E-015	      |	           5           3  -6.0173220572945521E-017
           5           4   2.1710064301849792E-015	      |	           5           4  -1.5178830414796963E-017
           5           5   2.1814249929681448     	      |	           5           5   2.2039997006752148     
           5           6  -2.4331781533144893E-014	      |	           5           6   2.2397829956790354E-015
           5           7   6.3699046037868254E-015	      |	           5           7  -1.9446250165700004E-015
           5           8  -7.2563483000110062E-015	      |	           5           8   3.5336317205647561E-015
           5           9 -0.60064611094315368     	      |	           5           9 -0.67013435561129131     
           5          10  -3.4757095812638291E-014	      |	           5          10  -7.5048285488226221E-016
           5          11   1.1322540127700705E-014	      |	           5          11   1.9073826719451221E-015
           5          12   4.6158823291399475E-015	      |	           5          12  -8.7901691134262233E-016
           5          13  -9.8782982032516731E-002	      |	           5          13  -1.4049553848001564E-003
           6           1  0.24361275681104622     	      |	           6           1  0.24361275681105393     
           6           2 -0.80863439374678936     	      |	           6           2 -0.80863439374679325     
           6           3  -5.1125029116304588E-014	      |	           6           3   3.0629360029081160E-015
           6           4  -1.4773448557886046E-013	      |	           6           4   4.3356075736519431E-015
           6           5  -2.4331781533144893E-014	      |	           6           5   2.2397829956790354E-015
           6           6   2.5051988916270922     	      |	           6           6   2.5051988916270966     
           6           7  -6.4537024518916542E-014	      |	           6           7  -1.3721602594402935E-014
           6           8  -9.9385912419733751E-014	      |	           6           8  -1.4543622912423709E-014
           6           9   5.3051919007649168E-015	      |	           6           9  -5.8768897866643135E-015
           6          10 -0.82613103097773599     	      |	           6          10 -0.82613103097776963     
           6          11  -1.4273623738418619E-013	      |	           6          11  -6.5449354021827050E-015
           6          12  -3.1333389807962717E-013	      |	           6          12  -4.3082674566338048E-015
           6          13  -5.7309447473249387E-015	      |	           6          13   1.7929487920385115E-015
           7           1  -8.9508933939923236E-014	      |	           7           1  -3.3515006236851547E-015
           7           2  -8.3490717186892391E-014	      |	           7           2   5.9234257184585872E-015
           7           3 -0.60064611094319265     	      |	           7           3 -0.67013435561129375     
           7           4  -4.7618159415565926E-015	      |	           7           4   3.9690473130349331E-015
           7           5   6.3699046037868254E-015	      |	           7           5  -1.9446250165700004E-015
           7           6  -6.4537024518916542E-014	      |	           7           6  -1.3721602594402935E-014
           7           7   1.9958696859473077     	      |	           7           7   2.2018807511864456     
           7           8   6.1409211049588548E-015	      |	           7           8  -8.3821838359199271E-015
           7           9   6.8278716014447238E-015	      |	           7           9  -2.1857515797307903E-016
           7          10  -1.1804510786801116E-013	      |	           7          10  -2.6920079462884486E-015
           7          11  0.23826125938149853     	      |	           7          11  -2.2952568011786814E-003
           7          12  -4.2762668406308052E-014	      |	           7          12  -4.7271214720369246E-016
           7          13   2.9094782139082908E-014	      |	           7          13   1.6471741505486030E-015
           8           1  -9.1304263381301632E-014	      |	           8           1  -1.8910301095544141E-015
           8           2  -2.3241997395987533E-013	      |	           8           2   5.7885360125974010E-015
           8           3   1.9255430583318755E-016	      |	           8           3   3.6776137690708295E-015
           8           4 -0.60064611094316334     	      |	           8           4 -0.67013435561129042     
           8           5  -7.2563483000110062E-015	      |	           8           5   3.5336317205647561E-015
           8           6  -9.9385912419733751E-014	      |	           8           6  -1.4543622912423709E-014
           8           7   6.1409211049588548E-015	      |	           8           7  -8.3821838359199271E-015
           8           8   1.9958696859472014     	      |	           8           8   2.2018807511864500     
           8           9   1.1109169140155496E-014	      |	           8           9  -5.5302984414140602E-015
           8          10  -3.2193630456688221E-013	      |	           8          10  -8.6729286862219469E-015
           8          11   2.6672240804877403E-014	      |	           8          11   2.0868723416000974E-014
           8          12  0.23826125938160925     	      |	           8          12  -2.2952568011831570E-003
           8          13  -8.7794355119188100E-015	      |	           8          13   8.7315137758947583E-015
           9           1  -2.1061027080447968E-014	      |	           9           1  -4.3780965221476420E-015
           9           2  -2.0166801164026711E-014	      |	           9           2   6.7110765413328744E-015
           9           3  -1.3711254354120685E-014	      |	           9           3   2.0309275094998473E-015
           9           4  -5.4522358849951102E-015	      |	           9           4  -1.8526846723432304E-015
           9           5 -0.60064611094315368     	      |	           9           5 -0.67013435561129131     
           9           6   5.3051919007649168E-015	      |	           9           6  -5.8768897866643135E-015
           9           7   6.8278716014447238E-015	      |	           9           7  -2.1857515797307903E-016
           9           8   1.1109169140155496E-014	      |	           9           8  -5.5302984414140602E-015
           9           9   1.9958696859471858     	      |	           9           9   2.2018807511864478     
           9          10   4.2459157265810415E-015	      |	           9          10  -6.8075954586383466E-016
           9          11  -3.0218882951516074E-014	      |	           9          11  -1.7897467362304409E-015
           9          12  -1.6634263411141777E-014	      |	           9          12   2.0751629581372466E-016
           9          13  0.23826125938162532     	      |	           9          13  -2.2952568011833374E-003
          10           1  -7.1906817042555360E-002	      |	          10           1  -7.1906817042565158E-002
          10           2  0.24552878676617224     	      |	          10           2  0.24552878676616285     
          10           3  -1.0835522103795586E-014	      |	          10           3  -1.3194751679725904E-015
          10           4  -3.2621996897293116E-014	      |	          10           4   4.5001602468251434E-015
          10           5  -3.4757095812638291E-014	      |	          10           5  -7.5048285488226221E-016
          10           6 -0.82613103097773599     	      |	          10           6 -0.82613103097776963     
          10           7  -1.1804510786801116E-013	      |	          10           7  -2.6920079462884486E-015
          10           8  -3.2193630456688221E-013	      |	          10           8  -8.6729286862219469E-015
          10           9   4.2459157265810415E-015	      |	          10           9  -6.8075954586383466E-016
          10          10   2.2726248856630713     	      |	          10          10   2.2726248856630282     
          10          11   1.4582189421438089E-013	      |	          10          11   8.5989732124157410E-015
          10          12   2.6760722831270010E-013	      |	          10          12   9.8570781542071080E-015
          10          13   1.1525010458178389E-014	      |	          10          13   1.5551682094823723E-015
          11           1  -1.0870995490376750E-014	      |	          11           1  -9.2927843873765874E-017
          11           2  -1.8310463861907492E-014	      |	          11           2   4.7597009306442267E-015
          11           3  -9.8782982032475375E-002	      |	          11           3  -1.4049553848003889E-003
          11           4  -7.8600320696499095E-015	      |	          11           4  -5.1629707453759674E-015
          11           5   1.1322540127700705E-014	      |	          11           5   1.9073826719451221E-015
          11           6  -1.4273623738418619E-013	      |	          11           6  -6.5449354021827050E-015
          11           7  0.23826125938149853     	      |	          11           7  -2.2952568011786814E-003
          11           8   2.6672240804877403E-014	      |	          11           8   2.0868723416000974E-014
          11           9  -3.0218882951516074E-014	      |	          11           9  -1.7897467362304409E-015
          11          10   1.4582189421438089E-013	      |	          11          10   8.5989732124157410E-015
          11          11   2.8809482488454878E-002	      |	          11          11   4.3553995506476640E-003
          11          12  -1.9528649530575324E-015	      |	          11          12  -9.5084530526974716E-016
          11          13  -2.7061686225165251E-016	      |	          11          13  -6.8955258170081533E-017
          12           1  -1.2873031950578005E-013	      |	          12           1  -7.9237455633652341E-016
          12           2  -7.0579433183959746E-014	      |	          12           2   9.0125550835970554E-017
          12           3   8.5541383004769344E-015	      |	          12           3   5.6985666185838409E-016
          12           4  -9.8782982032508432E-002	      |	          12           4  -1.4049553847991399E-003
          12           5   4.6158823291399475E-015	      |	          12           5  -8.7901691134262233E-016
          12           6  -3.1333389807962717E-013	      |	          12           6  -4.3082674566338048E-015
          12           7  -4.2762668406308052E-014	      |	          12           7  -4.7271214720369246E-016
          12           8  0.23826125938160925     	      |	          12           8  -2.2952568011831570E-003
          12           9  -1.6634263411141777E-014	      |	          12           9   2.0751629581372466E-016
          12          10   2.6760722831270010E-013	      |	          12          10   9.8570781542071080E-015
          12          11  -1.9528649530575324E-015	      |	          12          11  -9.5084530526974716E-016
          12          12   2.8809482488482814E-002	      |	          12          12   4.3553995506477577E-003
          12          13  -3.2915293754473660E-015	      |	          12          13  -3.2557913613381234E-016
          13           1  -1.3915814446704385E-014	      |	          13           1   1.6202463691374136E-015
          13           2  -1.4770284062557133E-014	      |	          13           2  -3.0807416892274513E-015
          13           3  -8.4984103088103590E-015	      |	          13           3  -2.9382014399628731E-015
          13           4   9.6717338998742350E-015	      |	          13           4  -2.3200842289017298E-015
          13           5  -9.8782982032516731E-002	      |	          13           5  -1.4049553848001564E-003
          13           6  -5.7309447473249387E-015	      |	          13           6   1.7929487920385115E-015
          13           7   2.9094782139082908E-014	      |	          13           7   1.6471741505486030E-015
          13           8  -8.7794355119188100E-015	      |	          13           8   8.7315137758947583E-015
          13           9  0.23826125938162532     	      |	          13           9  -2.2952568011833374E-003
          13          10   1.1525010458178389E-014	      |	          13          10   1.5551682094823723E-015
          13          11  -2.7061686225165251E-016	      |	          13          11  -6.8955258170081533E-017
          13          12  -3.2915293754473660E-015	      |	          13          12  -3.2557913613381234E-016
          13          13   2.8809482488486981E-002	      |	          13          13   4.3553995506481809E-003
[mmanathunga@psgcluster runs]$ diff -y CL ../../pr161/basis/STO-3G.SAD/CL
           1           1   2.2784645527746261     	      |	           1           1   2.2784645527746159     
           1           2 -0.81566933407639808     	      |	           1           2 -0.81566933407639497     
           1           3   2.1505211021142117E-013	      |	           1           3   5.9363214049750443E-015
           1           4  -8.5607748905691107E-015	      |	           1           4  -4.9474937160061514E-015
           1           5  -4.1083663301345664E-014	      |	           1           5   4.2187277455468954E-015
           1           6  0.14797638001643132     	      |	           1           6  0.14797638001643137     
           1           7   1.3601002238511377E-013	      |	           1           7   1.3433540401889573E-016
           1           8   1.3904976456152817E-014	      |	           1           8   3.9728364730610928E-016
           1           9   3.6631831429335076E-014	      |	           1           9  -4.3680222928109450E-016
           2           1 -0.81566933407639808     	      |	           2           1 -0.81566933407639497     
           2           2   2.3922580317436060     	      |	           2           2   2.3922580317436148     
           2           3   2.1003521495908068E-013	      |	           2           3  -1.8655485096317390E-014
           2           4   5.9957042415890379E-014	      |	           2           4   1.7608829264127358E-014
           2           5   4.0376765574199650E-014	      |	           2           5  -1.0564206250571971E-014
           2           6 -0.51184571927183509     	      |	           2           6 -0.51184571927183908     
           2           7   3.3800048451769093E-013	      |	           2           7   2.2831439089487856E-015
           2           8   3.3551663616777061E-014	      |	           2           8  -1.3155147400717156E-015
           2           9  -5.2566597021667154E-014	      |	           2           9  -1.0368878232236231E-015
           3           1   2.1505211021142117E-013	      |	           3           1   5.9363214049750443E-015
           3           2   2.1003521495908068E-013	      |	           3           2  -1.8655485096317390E-014
           3           3   2.0515533559389687     	      |	           3           3   2.0582650895468548     
           3           4  -2.4767939848463438E-002	      |	           3           4   3.4287958252955587E-002
           3           5  -1.8316183824686916E-002	      |	           3           5   1.3689286607186482E-002
           3           6   7.7267867477689042E-015	      |	           3           6  -1.4709887495713473E-015
           3           7 -0.26056088427339263     	      |	           3           7 -0.28850291616009915     
           3           8   9.1151082135611697E-002	      |	           3           8 -0.12420603465287902     
           3           9   6.7407300966267236E-002	      |	           3           9  -4.9588604668777077E-002
           4           1  -8.5607748905691107E-015	      |	           4           1  -4.9474937160061514E-015
           4           2   5.9957042415890379E-014	      |	           4           2   1.7608829264127358E-014
           4           3  -2.4767939848463438E-002	      |	           4           3   3.4287958252955587E-002
           4           4   2.1046152922994246     	      |	           4           4   2.0934283656656505     
           4           5  -7.2207807001990277E-003	      |	           4           5  -8.3646482392431554E-003
           4           6   2.0463561925004345E-014	      |	           4           6   4.5416143482859296E-016
           4           7   9.1151082141478310E-002	      |	           4           7 -0.12420603465287715     
           4           8 -0.45583965768137502     	      |	           4           8 -0.41587973632241804     
           4           9   2.6573949191649709E-002	      |	           4           9   3.0300427380299561E-002
           5           1  -4.1083663301345664E-014	      |	           5           1   4.2187277455468954E-015
           5           2   4.0376765574199650E-014	      |	           5           2  -1.0564206250571971E-014
           5           3  -1.8316183824686916E-002	      |	           5           3   1.3689286607186482E-002
           5           4  -7.2207807001990277E-003	      |	           5           4  -8.3646482392431554E-003
           5           5   2.1090396932545019     	      |	           5           5   2.1110400040796753     
           5           6  -4.5171705988877813E-014	      |	           5           6  -4.1974371620380600E-016
           5           7   6.7407300967915321E-002	      |	           5           7  -4.9588604668778256E-002
           5           8   2.6573949190492989E-002	      |	           5           8   3.0300427380300046E-002
           5           9 -0.47212235773869815     	      |	           5           9 -0.47967682085595625     
           6           1  0.14797638001643132     	      |	           6           1  0.14797638001643137     
           6           2 -0.51184571927183509     	      |	           6           2 -0.51184571927183908     
           6           3   7.7267867477689042E-015	      |	           6           3  -1.4709887495713473E-015
           6           4   2.0463561925004345E-014	      |	           6           4   4.5416143482859296E-016
           6           5  -4.5171705988877813E-014	      |	           6           5  -4.1974371620380600E-016
           6           6   2.1098663426886608     	      |	           6           6   2.1098663426886599     
           6           7  -1.2746871903192945E-013	      |	           6           7   2.2564629234449408E-015
           6           8  -3.6448176045188981E-014	      |	           6           8  -4.3115828577341462E-016
           6           9   2.3529912126589294E-014	      |	           6           9  -7.1253009055577573E-016
           7           1   1.3601002238511377E-013	      |	           7           1   1.3433540401889573E-016
           7           2   3.3800048451769093E-013	      |	           7           2   2.2831439089487856E-015
           7           3 -0.26056088427339263     	      |	           7           3 -0.28850291616009915     
           7           4   9.1151082141478310E-002	      |	           7           4 -0.12420603465287715     
           7           5   6.7407300967915321E-002	      |	           7           5  -4.9588604668778256E-002
           7           6  -1.2746871903192945E-013	      |	           7           6   2.2564629234449408E-015
           7           7   1.2634676188316336     	      |	           7           7   1.3780420724587248     
           7           8 -0.33545461675435478     	      |	           7           8  0.44992877471385900     
           7           9 -0.24807264798710599     	      |	           7           9  0.17963169181551286     
           8           1   1.3904976456152817E-014	      |	           8           1   3.9728364730610928E-016
           8           2   3.3551663616777061E-014	      |	           8           2  -1.3155147400717156E-015
           8           3   9.1151082135611697E-002	      |	           8           3 -0.12420603465287902     
           8           4 -0.45583965768137502     	      |	           8           4 -0.41587973632241804     
           8           5   2.6573949190492989E-002	      |	           8           5   3.0300427380300046E-002
           8           6  -3.6448176045188981E-014	      |	           8           6  -4.3115828577341462E-016
           8           7 -0.33545461675435478     	      |	           8           7  0.44992877471385900     
           8           8   1.9821334268602029     	      |	           8           8   1.8394568240265294     
           8           9  -9.7797565670697764E-002	      |	           8           9 -0.10976144760296935     
           9           1   3.6631831429335076E-014	      |	           9           1  -4.3680222928109450E-016
           9           2  -5.2566597021667154E-014	      |	           9           2  -1.0368878232236231E-015
           9           3   6.7407300966267236E-002	      |	           9           3  -4.9588604668777077E-002
           9           4   2.6573949191649709E-002	      |	           9           4   3.0300427380299561E-002
           9           5 -0.47212235773869815     	      |	           9           5 -0.47967682085595625     
           9           6   2.3529912126589294E-014	      |	           9           6  -7.1253009055577573E-016
           9           7 -0.24807264798710599     	      |	           9           7  0.17963169181551286     
           9           8  -9.7797565670697764E-002	      |	           9           8 -0.10976144760296935     
           9           9   2.0420570918207357     	      |	           9           9   2.0705578663769502      
```

**Comment by Madu86** [comment]
Of course, different initial guess may be due to different diagonalizers; but I would expect SCF to converge to an energy close to reference (ref: -1571.92725191 | quick-basis: -1571.927251599 | quick-sad: -1571.714717639). We can simply solve this problem by copying my CA and CL sad guess files into STO-3G.SAD folder.

**Comment by agoetz** [comment]
@Madu I made a few changes, please check the source code
- activated writing SCF info during SAD guess if writing SAD guess (WRSAD keyword)
- quit after SAD guess if writing of SAD guess is requested (WRSAD keyword)
- disable reading of SAD guess if writing of SAD guess is requested
(reading of SAD guess is on by default but falls back to compute if no SAD guess file is found)
- updated sadguess script to use 100 SCF iterations

I also added SAD guess files for all atoms for all basis sets. Convergence could have been set tighter for the lighter elements but DENSERMS=1.0e-6 should be OK. For heavier elements the UHF code that is used for atomic calculations is just too slow. For cc-pVDZ it took 24 minutes for Br for 14 SCF iterations and 1h 45 minutes for Ca for 57 SCF iterations.

Most transition metals are not or not well converged. This concerns all basis sets that do have transition metals without f functions, e.g. STO-3G, 3-21G, 6-31G. Some are mildly converged, others oscillate like crazy with errors never falling below 0.1, a far cry from 1e-6. 

No guess for elements with f functions was added since those are deactivated at the moment in any case (e.g. def2-SVP).

Short tests all passed locally for serial, MPI, and cuda code.

Please merge this PR if it looks good to you and the CI tests pass.

**Comment by Madu86** [comment]
> I also added SAD guess files for all atoms for all basis sets. Convergence could have been set tighter for the lighter elements but DENSERMS=1.0e-6 should be OK. For heavier elements the UHF code that is used for atomic calculations is just too slow. For cc-pVDZ it took 24 minutes for Br for 14 SCF iterations and 1h 45 minutes for Ca for 57 SCF iterations.
> 
> Most transition metals are not or not well converged. This concerns all basis sets that do have transition metals without f functions, e.g. STO-3G, 3-21G, 6-31G. Some are mildly converged, others oscillate like crazy with errors never falling below 0.1, a far cry from 1e-6.

Part of the problem is USCF implementation itself. If you take a closed shell system and force to run USCF, the number of steps taken to converge may be significantly different from SCF or it may even never converge. I observed this sort of strange stuff when working on USCF branch.

**Comment by Madu86** [comment]
@agoetz I have checked your changes. Everything looks good to me. CI, CUDA and CUDAMPI tests pass. I think this PR is ready to be merged. I can run some exhaustive tests after merging.

**Pull request merged**
