### PR TITLE
Temp fix for issue 97

### PR DESCRIPTION
**Pull request by Madu86**
I have disabled mpi runs for mp2 as a temporary solution for issue #97. We can enable mpi support once the issue has been properly investigated.

### CODE REVIEW

**Comment by Altaimorin** [comment]
This has been tested on serial and MPI versions and both worked OK.
By the way, what's the problem with the original MPI version? I tested ` mpirun -n 4 ./quick.MPI` with ene_wat2_mp2_631g.in and ene_wat2_mp2_631gss.in and both looked fine. I remembered that last year Vinicius found a bug on the MPI version but we fixed it eventually.

**Comment by agoetz** [comment]
@Altaimorin @Madu86 the MP2 tests for for `quick.cuda.MPI` on Expanse was hanging. Should this be working? I assumed both MPI and CUDA-MPI MP2 does not work because we have following in `runtest`:
```
    # Run the test case
    if [ "$buildtype" = 'mpi' ] || [ "$buildtype" = 'cudampi' ] && [ "$ismpirun" = 'yes' ] && [ "$ismp2" = 'no' ]; then
      mpirun -np "$ncores" "$qbindir/$qexe" "${i}.in"  2> /dev/null > /dev/null
    else
      "$qbindir/$qexe" "${i}.in"  2> /dev/null > /dev/null      
    fi
```
This just calls the executable without `mpirun -np $ncores` for MP2 tests.

**Comment by agoetz** [comment]
Let me investigate this again on Expanse as I was quite tired yesterday.

**Comment by Madu86** [comment]
@agoetz This has to be changed as follows. 

```
    # Run the test case
    if [ "$buildtype" = 'mpi' ] || [ "$buildtype" = 'cudampi' ] && [ "$ismpirun" = 'yes' ]; then
      $DO_PARALLEL "$qbindir/$qexe" "${i}.in"  2> /dev/null > /dev/null
    fi
```
I didn't fix this since I am working on another version. On PSG cluster, tests run fine with 32 cores (GCC/9.3.0, OpenMPI/4.0.4).

**Comment by agoetz** [comment]
OK. Let me try this. I will get back to you.

**Comment by agoetz** [comment]
OK, so now the MP2 tests pass but the geometry optimization test hangs (test 17, opt_wat_rhf_631g)
```
  # Run geometry optimization tests                                                                                                                                                   
...
    # Run the test case                                                                                                                                                               
    "$qbindir/$qexe" "$i.in" 2> /dev/null > /dev/null
```
So I changed this into
```
  # Run geometry optimization tests                                                                                                                                                   
...
    # Run the test case                                                                                                                                                               
    if [ "$buildtype" = 'mpi' ] || [ "$buildtype" = 'cudampi' ] && [ "$ismpirun" = 'yes' ]; then
        $DO_PARALLEL "$qbindir/$qexe" "${i}.in"  2> /dev/null > /dev/null
    else
        "$qbindir/$qexe" "$i.in" 2> /dev/null > /dev/null
    fi
```
but now the CUDA-MPI tests fail
```
Running test 17 of 18
RHF geometry optimization test: s and p basis functions
Final gradient: , Reference value: -0.0080327739. Failed
Final gradient: , Reference value: -0.0080734296. Failed
Final gradient: , Reference value: -0.0050844454. Failed
Final gradient: , Reference value: 0.0001470076. Failed
Final gradient: , Reference value: -0.0187432463. Failed
Final gradient: , Reference value: 0.0326077255. Failed
Final gradient: , Reference value: 0.0078857663. Failed
Final gradient: , Reference value: 0.0268166759. Failed
Final gradient: , Reference value: -0.0275232802. Failed

Minimized energy: , Reference value: -75.985330723. Failed
```
Same for test 18. The output contains ends after `@ End Reading Molecular Information`.
The serial, MPI, and CUDA versions pass all tests.
Note I set `DO_PARALLEL='mpirun -np 4'`. I manually ran the inputs and get a segfault with `-np 4` but it works with `-np 2`.

**Comment by agoetz** [comment]
We probably should move the above into an issue and close this PR.

**Comment by agoetz** [comment]
OK. I opened issue #102 to document failure of the optimization tests with quick.cuda.MPI using more than 2 tasks. I am closing this PR.

**Pull request closed without merging**
