### PR TITLE
Add error checks for builds enabling f-functions with GPU targets requiring legacy atomics (-DUSE_LEGACY_ATOMICS).

### LINKED ISSUE #326: GPU builds (CUDA, MPI+CUDA, HIP, and MPI+HIP) failing with GPU targets enabling `-DUSE_LEGACY_ATOMICS` and f-functions enabled
Several builds for CUDA and MPI+CUDA are failing on the MSU HPCC when GPU targets set the preprocessor directive `-DUSE_LEGACY_ATOMICS` and enable f-functions (CMake variable `-DENABLEF=TRUE`).  Build errors look like the following:

```
...
[ 79%] Built target octree_gpu
[ 79%] Building NVCC (Device) object src/cuda/CMakeFiles/quick_cuda_kernels.dir/quick_cuda_kernels_generated_gpu_type.cu.o
[ 79%] Building NVCC (Device) object src/cuda/CMakeFiles/quick_cuda_kernels.dir/quick_cuda_kernels_generated_gpu.cu.o
[ 79%] Building NVCC (Device) object src/cuda/CMakeFiles/quick_cuda_kernels.dir/quick_cuda_kernels_generated_gpu_get2e.cu.o
[ 79%] Building NVCC (Device) object src/cuda/CMakeFiles/quick_cuda_kernels.dir/quick_cuda_kernels_generated_gpu_get2e_grad_ffff.cu.o
QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1702): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((AGradx)*GRADSCALE) + (double)0.5); if ( AGradx < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[AStart]),(val2)); };
                                                                                                                                                                    ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1703): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((AGrady)*GRADSCALE) + (double)0.5); if ( AGrady < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[AStart + 1]),(val2)); };
                                                                                                                                                                    ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1704): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((AGradz)*GRADSCALE) + (double)0.5); if ( AGradz < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[AStart + 2]),(val2)); };
                                                                                                                                                                    ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1707): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((BGradx)*GRADSCALE) + (double)0.5); if ( BGradx < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[BStart]),(val2)); };
                                                                                                                                                                    ^
QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1708): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((BGrady)*GRADSCALE) + (double)0.5); if ( BGrady < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[BStart + 1]),(val2)); };
                                                                                                                                                                    ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1709): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((BGradz)*GRADSCALE) + (double)0.5); if ( BGradz < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[BStart + 2]),(val2)); };
                                                                                                                                                                    ^
QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1712): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((CGradx)*GRADSCALE) + (double)0.5); if ( CGradx < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[CStart]),(val2)); };
                                                                                                                                                                    ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1713): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((CGrady)*GRADSCALE) + (double)0.5); if ( CGrady < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[CStart + 1]),(val2)); };
                                                                                                                                                                    ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1714): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs((CGradz)*GRADSCALE) + (double)0.5); if ( CGradz < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[CStart + 2]),(val2)); };
                                                                                                                                                                    ^
QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1717): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs(((-AGradx-BGradx-CGradx))*GRADSCALE) + (double)0.5); if ( (-AGradx-BGradx-CGradx) < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[DStart]),(val2)); };
                                                                                                                                                                                                      ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1718): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs(((-AGrady-BGrady-CGrady))*GRADSCALE) + (double)0.5); if ( (-AGrady-BGrady-CGrady) < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[DStart + 1]),(val2)); };
                                                                                                                                                                                                      ^

QUICK/src/cuda/gpu_get2e_grad_ffff.cuh(1719): error: identifier "DEV_SIM_DBL_PTR_GRADULL" is undefined
      { unsigned long long int val2 = (unsigned long long int) (fabs(((-AGradz-BGradz-CGradz))*GRADSCALE) + (double)0.5); if ( (-AGradz-BGradz-CGradz) < (double)0.0) val2 = 0ull - val2; atomicAdd(&(DEV_SIM_DBL_PTR_GRADULL[DStart + 2]),(val2)); };
                                                                                                                                                                                                      ^

12 errors detected in the compilation of "QUICK/src/cuda/gpu_get2e_grad_ffff.cu".
CMake Error at quick_cuda_kernels_generated_gpu_get2e_grad_ffff.cu.o.RELEASE.cmake:278 (message):
  Error generating file
  QUICK/build_mpi_cuda_skylake_volta_v100_gcc12.3.0_openmpi5.0.0_cuda12.3.0/src/cuda/CMakeFiles/quick_cuda_kernels.dir//./quick_cuda_kernels_generated_gpu_get2e_grad_ffff.cu.o

gmake[2]: *** [src/cuda/CMakeFiles/quick_cuda_kernels.dir/quick_cuda_kernels_generated_gpu_get2e_grad_ffff.cu.o] Error 1
gmake[1]: *** [src/cuda/CMakeFiles/quick_cuda_kernels.dir/all] Error 2
gmake: *** [all] Error 2

```

Note that `-DUSE_LEGACY_ATOMICS` currently gets added in the CMake build for Kepler and Maxwell targets, as well as when GPU architectures are not explicity set but Kepler and/or Maxwell are supported for the detected CUDA version.

### PR DESCRIPTION
**Pull request by ohearnk**
Closes #326.

### CODE REVIEW

**Review by agoetz — CHANGES_REQUESTED** [review]
@Madu86 enabled legacy atomics in PR #346. However, Madu thinks that f gradients won't work on Kepler cards, see discussion in PR #346. I am not sure if anything else is required for HIP. I posted on Slack so we can discuss.
This means we don't have to deactivate targets that require legacy atomics. I am not sure about AMD / HIP though, so part of this PR may still be relevant.
If f gradients don't work on Kepler then we should a) catch this during runtime and b) update the test run scripts to ignore tests when a corresponding error message is printed. Alternatively we could just deactivate Kepler when f functions are requested - maybe that is best.
In any event the default should not be to quit cmake but rather to deactivate SM35 when ENABLEF=TRUE.

**Comment by Madu86** [comment]
Posting the following comment from Slack as per @ohearnk's request. 

> There is only 48 KB of memory configurable between L1 cache and shared memory on K80 card. We prioritize  L1 cache in the code: https://github.com/merzlab/QUICK/blob/master/src/cuda/gpu.cu#L153 for performance reasons, but even if we prioritize shared memory, the amount of available memory won't be enough.

**Comment by ohearnk** [comment]
@Madu86 I'm observing builds and tests now passing with f-function support on the K80s on MSU HPCC (built specifically for SM3.7).  Also see the (tight SCF) benchmarks showing in https://github.com/merzlab/QUICK/pull/347#issuecomment-2010452727.  I mentioned this to @agoetz in the meeting earlier today.  This may be a result of #346, though I did not bisect further.

Unless you think otherwise, I will re-enable f-function support with NVIDIA GPUs using LEGACY_ATOMICS.

**Review by agoetz — APPROVED** [review]
Looks good.

**Comment by agoetz** [comment]
We may have to disable HIP if we can't get HIP support into AmberTools. But for the moment I think we can leave it on. I will merge this PR.

**Pull request merged**
