### PR TITLE
filter out clang compiler

### PR DESCRIPTION
**Pull request by Altaimorin**
Fixed a typo in configure to filter out clang compiler on OS X.

### CODE REVIEW

**Comment by Madu86** [comment]
@Altaimorin So this just filters out clang compiler. Have you tried to use clang compiler? Of course, there is no option in the configure script; but you can generate make.in file for GNU. modify it for clang and see what happens with compilation. If this works fine, we should consider adding clang option for compiler list.

**Comment by Madu86** [comment]
@Altaimorin Have you checked what happens with intel compiler on OS X? @agoetz Do we know if clang, intel and gnu compilers work fine on OS X with cmake build? If yes, we should make sure configure script is also capable of doing this.

**Comment by agoetz** [comment]
I have not yet tested the CMake build system on macOS. I do not have the Intel compiler install on any macOS system. I can try gnu and clang on the weekend.

**Comment by agoetz** [comment]
@Madu86 Can we close this PR?

**Comment by Madu86** [comment]
Yeah, this issue is no longer a concern.

**Pull request closed without merging**
