### PR TITLE
Improvements to Boys function

### PR DESCRIPTION
**Pull request by Madu86**
This PR contains updates to Boys function and should fix issue #64 in serial and MPI versions. Specifically, I have updated the cutoff for using upward recurrence relations in FmT subroutine (and FmT device kernel). The cutoff was determined by fitting Boys function values from QUICK FmT subroutine to the values from MIRP boys_exact function.
I have also added the option to link and use MIRP Boys function in the build system. MIRP library and dependencies must be compiled and MIRP_HOME, MIRP_DEP_HOME must be set before configuring QUICK. The option currently works only with --shared option.

### CODE REVIEW

**Comment by Altaimorin** [comment]
cc-pvtz basis set needs to be added for testing.

**Comment by Madu86** [comment]
Please use this: https://github.com/merzlab/QUICK/blob/QUICK-20.03/basis/CC-PVTZ.BAS. Make sure to update basis_link file accordingly.

**Comment by Altaimorin** [comment]
Both serial and MPI versions have been tested and worked fine on ICER HPCC.

**Comment by Madu86** [comment]
@Altaimorin Thanks! Merging the PR..

**Pull request merged**
