### PR TITLE
More CMake updates

### PR DESCRIPTION
**Pull request by multiplemonomials**
This PR adds a couple things I missed in the original
- Fix optimization flags to use O2
- Fix permissions on installed tests
- Remove useless libxc_mpi target

It also fixes some incompatibilities with Amber.

### CODE REVIEW

**Review by agoetz — APPROVED** [review]
Looks good. Tests pass on chinotto with gcc 4.8.5, openmpi 4.0.5 and CUDA 11.0. Going to merge.

**Comment by multiplemonomials** [comment]
oh dang the workflow died because of the runtest name, hang on

**Comment by agoetz** [comment]
I tested before changing back to runtest.

**Comment by agoetz** [comment]
I am fine with calling it quick_runtest. Any objections from Madu?

**Comment by multiplemonomials** [comment]
fwiw, I changed it to quick_runtest because it was less likely to conflict with other installed apps, but @vwcruzeiro asked me to change it.

**Comment by Madu86** [comment]
@agoetz No, we will have to change the name in configure build system too.

**Comment by vwcruzeiro** [comment]
Hello @multiplemonomials . I think you misunderstood my message. Please move bin/quick_runtest into runtest (notice: not inside the bin folder). Thank you.

**Comment by multiplemonomials** [comment]
Oh OK

**Comment by vwcruzeiro** [comment]
Merging this PR.

**Pull request merged**
