### PR TITLE
New tests 

### PR DESCRIPTION
**Pull request by Madu86**
I have updated the test suite with new test cases. Specifically, I have added elementary tests for STO-3G, 3-21G, 6-31G, 6-31G*, 6-31G**, cc-pVDZ, def2-svp, def2-svpd basis sets. These are just HF energy calculations and the goal is to make sure that compounds containing H, Li, Be, B, C, N, O, F, Na, Mg, Al, Si, P, S, Cl, K, Ca, Br, I elements will run SCF. The compounds I have selected are AlH3, BH3, BeH2, CaCal2, CH4, HBr, H2O, KCl, LiF, Ki, MgO, NH4, NaCl, PH3/PO4-3, SO2 and SiH4. 

For 6-31G, 6-31G* and 6-31G** basis sets,  CaCal2, HBr and KCl SAD guess take too long (> 1 min). For cc-pvDZ AlH3, MgO, PH3, SiH4, SO2, CaCl2, HBr, KCl, NaCl take too long. For def2-svpd CaCl2, HBr and HI take too long. Therefore I have temporarily disabled them. @Altaimorin is currently working on saving SAD guess. We can enable these tests when his implementation is in place. 

Apart from the above tests, I have added new point charge gradient tests and geometry optimization tests. @agoetz @vwcruzeiro Please check and let me know what else we need. 

@vwcruzeiro Can we extract energies and  gradients from reference outputs when we run amber test script? I see you have saved reference files for individual components. In this way we won't keep files with duplicate information inside the saved folder.

### CODE REVIEW

**Comment by Madu86** [comment]
As @vwcruzeiro requested, I have changed HF tests with def2-sv(p), def2-svp, def2-svpd basis sets into B3LYP gradient tests. These are now in place. Furthermore, since we have a long test list now, I updated the runtest script to print a summary of test results at the very end.

**Comment by vwcruzeiro** [comment]
@Madu86 , great! You mentioned that a bug fix was need for the DFT cases. Is that in place now?

**Comment by Madu86** [comment]
@vwcruzeiro  Yes, I have fixed that. Let me make some few more changes.

**Comment by Madu86** [comment]
@vwcruzeiro So I noticed that some tests that pass in serial version fails in cuda version. When I checked the .ene.dif files of one example, I found that cuda version is taking two more scf iterations to reach the convergence than the serial version. 

CUDA:

```
                                         SCF ENERGY
------------------------------------------------------------------------------------------------------------------------
NCYC       ENERGY         DELTA_E      SCF_TIME  DII_CYC   DII_TIME   O_TIME  DIAG_TIME    MAX_ERR    RMS_CHG    MAX_CHG
------------------------------------------------------------------------------------------------------------------------
|  1    -26.542122075      ------         0.029     1        0.01      0.02      0.01    0.1302E+01  0.4635E-01  0.4689E+00
|  2    -26.558747177  0.166251E-01       0.017     2        0.01      0.01      0.01    0.7706E-01  0.1359E-01  0.2493E+00
|  3    -26.572377842  0.136307E-01       0.016     3        0.01      0.01      0.01    0.4104E-01  0.4072E-02  0.7417E-01
|  4    -26.576581737  0.420390E-02       0.016     4        0.01      0.01      0.01    0.2049E-02  0.3781E-03  0.5726E-02
|  5    -26.576600885  0.191479E-04       0.016     5        0.01      0.01      0.01    0.2998E-03  0.4485E-04  0.6179E-03
|  6    -26.576601348  0.462942E-06       0.016     6        0.01      0.01      0.01    0.8861E-04  0.1324E-04  0.1425E-03
|  7    -26.576601375  0.271399E-07       0.016     7        0.01      0.01      0.01    0.9506E-05  0.1640E-05  0.1442E-04
    | -------------- 2E-INT CUTOFF CHANGE TO 0.1000E-08 ------------
|  8    -26.576601453  0.785627E-07       0.016     8        0.01      0.01      0.01    0.3183E-06  0.1908E-05  0.5426E-04
|  9    -26.576601454  0.888729E-10       0.016     9        0.01      0.01      0.01    0.4099E-07  0.2266E-06  0.6386E-05
------------------------------------------------------------------------------------------------------------------------
| REACH CONVERGENCE AFTER   9 CYLCES
| MAX ERROR = 0.409875E-07   RMS CHANGE = 0.226633E-06   MAX CHANGE = 0.638581E-05
 -----------------------------------------------
 ALPHA ELECTRON DENSITY    =    4.0000057649
 BETA ELECTRON DENSITY     =    4.0000057649
 ELECTRONIC ENERGY    =   -34.625897885
 CORE_CORE REPULSION  =     8.049296432
 TOTAL ENERGY         =   -26.576601454
```

Serial: 
```
                                         SCF ENERGY
------------------------------------------------------------------------------------------------------------------------
NCYC       ENERGY         DELTA_E      SCF_TIME  DII_CYC   DII_TIME   O_TIME  DIAG_TIME    MAX_ERR    RMS_CHG    MAX_CHG
------------------------------------------------------------------------------------------------------------------------
|  1    -26.554174340      ------         0.187     1        0.00      0.19      0.00    0.1302E+01  0.4617E-01  0.4699E+00
|  2    -26.558566287  0.439195E-02       0.221     2        0.00      0.22      0.00    0.7848E-01  0.1381E-01  0.2529E+00
|  3    -26.572226393  0.136601E-01       0.220     3        0.00      0.22      0.00    0.4185E-01  0.4135E-02  0.7538E-01
|  4    -26.576586192  0.435980E-02       0.219     4        0.00      0.22      0.00    0.2062E-02  0.3589E-03  0.5320E-02
|  5    -26.576601144  0.149521E-04       0.224     5        0.00      0.22      0.00    0.2973E-03  0.3631E-04  0.5839E-03
|  6    -26.576601398  0.253728E-06       0.240     6        0.00      0.24      0.00    0.7109E-04  0.1127E-04  0.1299E-03
|  7    -26.576601410  0.123437E-07       0.221     7        0.00      0.22      0.00    0.4202E-05  0.6420E-06  0.5783E-05
------------------------------------------------------------------------------------------------------------------------
| REACH CONVERGENCE AFTER   7 CYLCES
| MAX ERROR = 0.420159E-05   RMS CHANGE = 0.642031E-06   MAX CHANGE = 0.578324E-05
 -----------------------------------------------
 ALPHA ELECTRON DENSITY    =    4.0000064340
 BETA ELECTRON DENSITY     =    4.0000064340
 ELECTRONIC ENERGY    =   -34.625897842
 CORE_CORE REPULSION  =     8.049296432
 TOTAL ENERGY         =   -26.576601410
```

And dacdif gives me this with a failure message. 

```
6c6
< ------------------------------------------------------------------------------------------------------------------------
>     | -------------- 2INT CUTOFF CHANGE TO 0.1000E-8 ------------
7c7
<  -----------------------------------------------
> ------------------------------------------------------------------------------------------------------------------------
8c8
<  ALPHA ELECTRON DENSITY    =    4.0000064340
>  -----------------------------------------------
9c9
<  BETA ELECTRON DENSITY     =    4.0000064340
>  ALPHA ELECTRON DENSITY    =    4.0000057649
10c10
<  ELECTRONIC ENERGY    =   -34.625897842
>  BETA ELECTRON DENSITY     =    4.0000057649
11c11
<  CORE_CORE REPULSION  =     8.049296432
>  ELECTRONIC ENERGY    =   -34.625897885
12c12
<  TOTAL ENERGY         =   -26.576601410
>  CORE_CORE REPULSION  =     8.049296432
13c13
<  @ End Energy calculation
>  TOTAL ENERGY         =   -26.576601454
```

Any idea how to fix this?

**Comment by agoetz** [comment]
> Any idea how to fix this?
dacdif will ignore lines that begin with `|`. This line begins with a space
```
    | -------------- 2E-INT CUTOFF CHANGE TO 0.1000E-08 ------------
```
If you change this to print the bar at the beginning of the line, the diff should work as expected.

**Comment by agoetz** [comment]
This looks like a reasonable test list to me.

**Review by agoetz — COMMENTED** [review]
Looks good to me.

Do we have a short/full test suite? I don't think it's always required to run too many different basis sets for each molecule. On the other hand I would add def2-svp for some of the larger tests and point charge tests that you added. Could run these on GPU by default since GPU is fast.

**Comment by Madu86** [comment]
>     | -------------- 2E-INT CUTOFF CHANGE TO 0.1000E-08 ------------
> If you change this to print the bar at the beginning of the line, the diff should work as expected.

@agoetz Oh I didn't notice the line without pipe. I am getting old. Thanks for pointing out.

**Comment by Madu86** [comment]
> Do we have a short/full test suite? I don't think it's always required to run too many different basis sets for each molecule. On the other hand I would add def2-svp for some of the larger tests and point charge tests that you added. Could run these on GPU by default since GPU is fast.

@agoetz Currently, we only have one. But I am working on having a short test suite as well. I will also add def2-svp basis set for point charge tests in GPU version.

**Comment by agoetz** [comment]
I see you have tests `grad_HI_b3lyp_def2sv_p.in` and `grad_HI_b3lyp_def2svp.in`. How do the energies compare to Gaussian? Do we have ECPs? I do not see ECPs.

**Comment by Madu86** [comment]
@agoetz Horribly different. I am temporarily disabling HI tests.

**Comment by Madu86** [comment]
No we don't have ECPs.

**Comment by agoetz** [comment]
The def2-SVP and def2-SV(P) basis sets are developed with a 28-electron ECP. I asked Chi to check the basis sets. We can't add elements that we do not support if we do not support ECPs.

**Comment by Madu86** [comment]
@agoetz I have updated runtest script again. We have two main test lists: short (just 26 tests) and long (139 tests). The default is set to short test (i.e. when running `make test`). If you want to run full test suite you should do: `./runtest --full`.  I have also updated point charge tests of cuda and cudampi versions with def2 basis sets.

**Comment by agoetz** [comment]
We should check if the ECP code works. After the Amber code freeze and after revising the multi-GPU paper.

**Comment by agoetz** [comment]
Are you done with the tests? Shall I test this?

**Comment by Madu86** [comment]
@agoetz @vwcruzeiro I am done with this. Please test and merge.

**Comment by agoetz** [comment]
The short test list should contain a selection of tests that execute in short time. 
These following tests are contenders to be removed from the short CPU list. They account for > 20 minutes out of 28 minutes. If there is someting critical, be judicious in keeping it and justify why.
```
ene_psb5_rhf_631gss.out:| Job cpu time:  0 days  0 hours  2 minutes  3.5 seconds.
grad_c10h9o2s_b3lyp_def2svp.out:| Job cpu time:  0 days  0 hours  5 minutes 35.2 seconds.
grad_ch3conhch3_b3lyp_ccpvdz.out:| Job cpu time:  0 days  0 hours  2 minutes 32.1 seconds.
grad_daspi_meoh_b3lyp_sto3g.out:| Job cpu time:  0 days  0 hours  1 minutes 41.5 seconds.
grad_hbdi_meoh_libxc_blyp_sto3g.out:| Job cpu time:  0 days  0 hours  2 minutes  3.5 seconds.
grad_naip_meoh_libxc_pbeh_sto3g.out:| Job cpu time:  0 days  0 hours  2 minutes 30.6 seconds.
grad_ncnaip_b3lyp_sto3g.out:| Job cpu time:  0 days  0 hours  2 minutes 50.1 seconds.
grad_psb3_b3lyp_631gss.out:| Job cpu time:  0 days  0 hours  1 minutes  4.1 seconds.
grad_rpsb_meoh_rhf_sto3g.out:| Job cpu time:  0 days  0 hours  1 minutes 17.0 seconds.
```
These three tests also take long on GPU. Contenders to be removed from the short GPU list.
```
grad_hbdi_meoh_libxc_blyp_def2sv_p.out:| Job cpu time:  0 days  0 hours  1 minutes 21.3 seconds.
grad_naip_meoh_libxc_pbeh_def2svp.out:| Job cpu time:  0 days  0 hours  1 minutes 44.9 seconds.
grad_ncnaip_b3lyp_631gss.out:| Job cpu time:  0 days  0 hours  1 minutes 48.6 seconds.
```
I suspect this may be due to one-electron integral gradients (i.e. point charges)? To test the point charges it should be sufficient to retain only a handful of point charges.

**Comment by Madu86** [comment]
I have updated the runtest script with `--nolog` flag to disable writing runtest.log. I have also added a new target to main Makefile (fulltest: https://github.com/Madu86/QUICK/blob/fix109/Makefile#L147-L152) to run full test suite if anyone wants. Furthermore, I have updated CI action files (both for make and cmake build systems: https://github.com/Madu86/QUICK/blob/fix109/.github/workflows/mpi.yml#L25, https://github.com/Madu86/QUICK/blob/fix109/.github/workflows/mpi.yml#L56)

**Comment by agoetz** [comment]
The short tests are now really short. Times on chinotto, rounded to minutes
```
2 GPU: 3 min 
1 GPU: 4 min
2 CPU: 3 min
1 CPU: 4 min
```

**Comment by agoetz** [comment]
All short tests pass on chinotto (gnu 8.3.1, openmpi 4.0.5, CUDA 11.0). However, the counts in the summary are not right:
```
cudampi version:
    Energy tests: 0/0 (failed/total)
    Gradient tests: 0/1 (failed/total)
    Optimization tests: 0/0 (failed/total)
    Total tests: 0/17 (failed/total)

cuda version:
    Energy tests: 0/0 (failed/total)
    Gradient tests: 0/1 (failed/total)
    Optimization tests: 0/0 (failed/total)
    Total tests: 0/17 (failed/total)

mpi version:
    Energy tests: 0/12 (failed/total)
    Gradient tests: 0/3 (failed/total)
    Optimization tests: 0/2 (failed/total)
    Total tests: 0/17 (failed/total)

serial version:
    Energy tests: 0/11 (failed/total)
    Gradient tests: 0/3 (failed/total)
    Optimization tests: 0/3 (failed/total)
    Total tests: 0/17 (failed/total)
```

**Comment by agoetz** [comment]
@Madu86 I did run all the tests at once like this
```
export DO_PARALLEL='mpirun -np 2'
./runtest --nolog > runtest.log
```

I see that you are still keeping a hidden logfile `.quick.runtest.log` and that you use this to parse the summary. I don't see that you remove this hidden file at the beginning of the script so if there is a leftover file from an aborted test run it will get appended and mess up your summary. This is what may have happened? So probably you should remove the `-a` from
```
# create runtest.log                                                                                                   
echo "" | tee -a $QUICK_HOME/.quick.runtest.log
```

Also, you should use different temporary log files for different test types. With the current setup parallel runs of different test types (e.g. `--serial` and `--mpi` etc) will overwrite each other's `.quick.runtest.log`). Same holds for other flags. So probably these files should be called something like `.quick.runtest.$arch.$testtype.log` where arch can be any of serial, mpi, cuda, cudampi, all and testtype can be all, ene, grad, opt.

**Comment by Madu86** [comment]
@agoetz Good catch. There were two problems. The first is one you pointed out. The second is that when preparing the summary, script was considering the total number of tests as the ones from serial/mpi test list although this is different for cuda. These issues have been fixed. When I run the script with `ctrl+z, fg` I have the following at the very end of my individual log files. 

```
[1]   Done                    ./runtest --serial --nolog > runtest.serial.log
[2]-  Done                    ./runtest --mpi --nolog > runtest.mpi.log
[3]+  Done                    ./runtest --cuda --nolog > runtest.cuda.log

[mmanathunga@hsw229 fix109]$ tail -10 runtest.cuda.log 

======================== Test Summary ========================

cuda version:
    Energy tests: 0/12 (failed/total)
    Gradient tests: 0/8 (failed/total)
    Optimization tests: 1/3 (failed/total)
    Total tests: 1/23 (failed/total)

==============================================================
[mmanathunga@hsw229 fix109]$ tail -10 runtest.mpi.log 

======================== Test Summary ========================

mpi version:
    Energy tests: 0/11 (failed/total)
    Gradient tests: 0/3 (failed/total)
    Optimization tests: 1/3 (failed/total)
    Total tests: 1/17 (failed/total)

==============================================================
[mmanathunga@hsw229 fix109]$ tail -10 runtest.serial.log 

======================== Test Summary ========================

serial version:
    Energy tests: 0/11 (failed/total)
    Gradient tests: 0/3 (failed/total)
    Optimization tests: 1/3 (failed/total)
    Total tests: 1/17 (failed/total)

==============================================================

```
 
Note that I intentionally changed the input of one geometry optimization calculation (which is failed) for testing purposes.

**Comment by agoetz** [comment]
I am going to test this now.

**Comment by agoetz** [comment]
Lots of MPI and CUDA-MPI tests fail. Seem like all are due to verbose output from SAD guess. Did you make any changes for the SAD guess? Weird that this is only for MPI. For example for ene_psb5_rhf_631g:
Serial code:
```
@ Begin SAD initial guess

 For Atom Kind =    1
 ELEMENT = C
 BASIS FUNCTIONS =    9
 For Atom Kind =    2
 ELEMENT = H
 BASIS FUNCTIONS =    2
 For Atom Kind =    3
 ELEMENT = N
 BASIS FUNCTIONS =    9

 @ Finish SAD initial guess
```
MPI code:
```
 @ Begin SAD initial guess

 For Atom Kind =    1
 ELEMENT = C
 BASIS FUNCTIONS =    9

 @ Begin Energy Calculation


| SCF CYCLE      =        1      TIME      =     0.04
| RMS CHANGE     = 0.149950E+00  MAX CHANGE= 0.820201E+00

| SCF CYCLE      =        2      TIME      =     0.04
| RMS CHANGE     = 0.797517E-01  MAX CHANGE= 0.329362E+00

| SCF CYCLE      =        3      TIME      =   0.04
| DIIS CYCLE     =        1      MAX ERROR = 0.404829E-01
| RMS CHANGE     = 0.137215E-01  MAX CHANGE= 0.604631E-01
...
...
```

**Comment by agoetz** [comment]
Let me do a fresh checkout to make sure this is not due to some local changes I made.

**Comment by Madu86** [comment]
@agoetz I didn't do anything there. Probably something happening after merging Chi's PR?

**Comment by agoetz** [comment]
Which PR? The SAD guess PR is still open, isn't it?

**Comment by Madu86** [comment]
@agoetz Yeah, you are right. I just noticed that some MPI tests in CI failed. Looks like I messed up something. Let me check.

**Comment by agoetz** [comment]
Yeah, all the ene tests fail with mpi because they spit out SAD guess SCF info like we removed long time ago.

**Comment by agoetz** [comment]
As a consequence the diff gets messed up because it picks `@ Begin Energy Calculation` from the SAD guess.

**Comment by Madu86** [comment]
Yes, let me fix this.

**Comment by Madu86** [comment]
@agoetz There was an argument mismatch in a sub call. I have fixed this. I was wondering why compiler never complaint about this..

**Comment by agoetz** [comment]
I tested this locally. All short tests pass. I will merge this now.

**Pull request merged**
