### PR TITLE
QUICK_DL-Find

### PR DESCRIPTION
**Pull request by akhilshajan**
I made all of the changes necessary. Dl-Find is fully operational and has passed the make fulltest. I attempted to make adjustments for BADSCF but was unable to do so due to time constraints. A few commits were done for BADSCF conditions, but they were later reversed. @agoetz  could you please review it and let me know if any changes are required?

### CODE REVIEW

**Comment by Madu86** [comment]
@akhilshajan Your branch is way behind current merzlab master. I tried to rebase but got lost halfway through because the comments are not meaningful/ a single commit has too many changes. So I am not sure what changes to keep. Can you please rebase this branch on top of merzlab/master? Here is a tutorial: https://www.freecodecamp.org/news/the-ultimate-guide-to-git-merge-and-git-rebase/.

**Comment by Madu86** [comment]
Ok, I did the rebasing. However, the dlfind tests fail. Problem is that there are no reference test output files. 

```
cp: cannot stat ‘/home/madu/quick_dlfind/test/saved/opt_hsoh_pbe0_def2svp.out’: No such file or directory
Running test 19 of 23
Oxadisulfane: DFT DL-Find geometry test with s, p and d basis functions
awk: fatal: cannot open file `opt_hsoh_pbe0_def2svp.ref.out' for reading (No such file or directory)
diffing opt_hsoh_pbe0_def2svp.ref.opt with opt_hsoh_pbe0_def2svp.opt
PASSED
==============================================================
awk: fatal: cannot open file `opt_hsoh_pbe0_def2svp.ref.out' for reading (No such file or directory)
diffing opt_hsoh_pbe0_def2svp.ref.dipole with opt_hsoh_pbe0_def2svp.dipole
PASSED
==============================================================

cp: cannot stat ‘/home/madu/quick_dlfind/test/saved/opt_c3h4_rhf_631g.out’: No such file or directory
Running test 20 of 23
Allene: RHF DL-Find geometry test with s and p basis functions
awk: fatal: cannot open file `opt_c3h4_rhf_631g.ref.out' for reading (No such file or directory)
diffing opt_c3h4_rhf_631g.ref.opt with opt_c3h4_rhf_631g.opt
file ddtmp.opt_c3h4_rhf_631g.ref.opt is short
possible FAILURE:  check opt_c3h4_rhf_631g.opt.dif
==============================================================
awk: fatal: cannot open file `opt_c3h4_rhf_631g.ref.out' for reading (No such file or directory)
diffing opt_c3h4_rhf_631g.ref.dipole with opt_c3h4_rhf_631g.dipole
PASSED
==============================================================

cp: cannot stat ‘/home/madu/quick_dlfind/test/saved/opt_c2h5rad_b3lyp_631gss.out’: No such file or directory
Running test 21 of 23
Ethyl radical: UDFT B3LYP DL-FIND geometry optimization
awk: fatal: cannot open file `opt_c2h5rad_b3lyp_631gss.ref.out' for reading (No such file or directory)
diffing opt_c2h5rad_b3lyp_631gss.ref.opt with opt_c2h5rad_b3lyp_631gss.opt
file ddtmp.opt_c2h5rad_b3lyp_631gss.ref.opt is short
possible FAILURE:  check opt_c2h5rad_b3lyp_631gss.opt.dif
==============================================================
awk: fatal: cannot open file `opt_c2h5rad_b3lyp_631gss.ref.out' for reading (No such file or directory)
diffing opt_c2h5rad_b3lyp_631gss.ref.dipole with opt_c2h5rad_b3lyp_631gss.dipole
PASSED
==============================================================

cp: cannot stat ‘/home/madu/quick_dlfind/test/saved/opt_c2hrad_uhf_ccpvdz.out’: No such file or directory
Running test 22 of 23
Ethynyl radical: UHF DL-Find geometry test with s, p and d basis functions
awk: fatal: cannot open file `opt_c2hrad_uhf_ccpvdz.ref.out' for reading (No such file or directory)
diffing opt_c2hrad_uhf_ccpvdz.ref.opt with opt_c2hrad_uhf_ccpvdz.opt
file ddtmp.opt_c2hrad_uhf_ccpvdz.ref.opt is short
possible FAILURE:  check opt_c2hrad_uhf_ccpvdz.opt.dif
==============================================================
awk: fatal: cannot open file `opt_c2hrad_uhf_ccpvdz.ref.out' for reading (No such file or directory)
diffing opt_c2hrad_uhf_ccpvdz.ref.dipole with opt_c2hrad_uhf_ccpvdz.dipole
PASSED
==============================================================
```

**Comment by Madu86** [comment]
@akhilshajan Slave ranks still print stuff from dlfind into fort.2021 file in mpi versions. This has to be properly fixed.

**Comment by akhilshajan** [comment]
> @akhilshajan You have put an exit statement inside a conditional statement that is only executed by the master rank. This means that the master rank will exit while slave ranks wait forever thus leading to a program hangup. Please fix this and test.

Fixed the issue with placing just the print statement inside the if condition

**Comment by Madu86** [comment]
@akhilshajan I just enabled ALLOW_BAD_SCF support. Can you please test all 4 versions quickly?

**Comment by Madu86** [comment]
Everything looks good. I am merging this PR.

**Pull request merged**
