### PR TITLE
add DEF2-SV\(P\).BAS 

### PR DESCRIPTION
**Pull request by Altaimorin**

### CODE REVIEW

**Comment by agoetz** [comment]
Thanks @Altaimorin . Please use a file name without special characters. I suggest `DEF2-SV_P.BAS`. You will also have to edit the `basis_link` file (@Madu86 can coment if there are any pitfalls).

**Comment by Altaimorin** [comment]
The name of `DEF2-SV(P).BAS` has been changed to `DEF2-SV_P.BAS` and it has been added to the `basis_link` file. Thank you for your reminder.

**Comment by agoetz** [comment]
@Altaimorin you have to edit the `basis_link` file so users can use the correct basis set name def2-SV(P).

@Madu86 why do we have two files `6-311GSS.BAS` and `6-311GDP.BAS` that are identical? Why do we not have keywords 6-31G(d) and 6-31G(d,p)? Instead of S I think we should keep D and DP in the file names for the Pople basis sets. We should have

6-31G(d) = 6-31G*, filename 6-31GD.BAS
6-31G(d,p) = 6-31G**, filename 6-31GDP.BAS
6-311G(d) = 6-311G*, filename 6-31GD.BAS
6-311G(d,p) = 6-311G**, filename 6-31GDP.BAS

@Altaimorin or @madu please add missing keywords, remove redundant .BAS files, and make sure the basis sets files are complete (i.e. cover all available elements). Thanks.

**Comment by Madu86** [comment]
@agoetz hm, not sure. We should definitely get rid of them. Another thing, we should store sad guess for some alkali metals (Li, Na, K), alkaline-earth metals (Mg, Ca) and halogens (F, Cl, Br, I)  at least for 6-31G, 6-31G*, 6-31G**, cc-pvDZ, def2-svp, def2-svpd basis sets. We have issue #123  opened for this.

**Comment by Altaimorin** [comment]
@agoetz 
I'm going to remove `6-311GDP.BAS` and added the missing keywords.

**Comment by agoetz** [comment]
Thanks @Altaimorin . Please do also check that our basis set files are complete.

@Madu86 I agree, we should store the SAD guess. It does not matter much for the CPU code, but can take a good fraction of time for GPU based single point calculations of smaller molecules. I did not know that we can already do that. If we do have that capability, why don't we store the guess for all atoms? Can't we automate generation with a simple shell script?

**Comment by Altaimorin** [comment]
Where did you get `6-31G2DF2PD.BAS`? It's not in https://www.basissetexchange.org/. There's `6-31G(3df,3pd)` which has fewer atoms in it.

**Comment by Altaimorin** [comment]
@agoetz 
All files have been checked complete.

**Comment by Madu86** [comment]
>  If we do have that capability, why don't we store the guess for all atoms? Can't we automate generation with a simple shell script?

@agoetz Sure we can. @Altaimorin is working on that.

**Comment by Madu86** [comment]
@agoetz @Altaimorin I am merging this PR for checking new test suite. We can carry out the SAD guess discussion in issue #123.

**Review by Madu86 — APPROVED** [review]

**Pull request merged**
