### PR TITLE
Fix for issue #129

### PR DESCRIPTION
**Pull request by Madu86**
It turns out that the issue #129 is caused by a sloppy conditional statement in DFT grid generation code. This has been fixed. We have to add more dft grids somewhere down the line. SG1 is not good for Alkali, Alkaline earth and halogens. See the following b3lyp/def2-svp energy comparison of different compounds (covers all elements except HI in current scope) between QUICK and a reference code.

```
AlH3 ref: -243.781735361, quick: -243.781908364 diff: 0.00017300300001465985
BeH2 ref: -15.8603827816, quick: -15.860404278 diff: 2.1496400000486915e-05
BH3 ref: -26.5734175368, quick: -26.573418543 diff: 1.006199997988233e-06
CaCl2 ref: -1593.12904130, quick: -1593.129022946 diff: -1.835399984884134e-05
CH4 ref: -40.4887262332, quick: -40.488727144 diff: 9.108000043056563e-07
H2O ref: -76.3417420591, quick: -76.341742540 diff: 4.808999989336371e-07
HBr ref: -2574.38724809, quick: -2574.385829155 diff: -0.0014189349999469414
KCl ref: -1059.99125206, quick: -1059.990853939 diff: -0.00039812099998925987
LiF ref: -107.320962139, quick: -107.320819934 diff: -0.00014220500000305947
MgO ref: -275.104031960, quick: -275.104224198 diff: 0.00019223800001100244
NaCl ref: -622.390032414, quick: -622.389903171 diff: -0.0001292429999466549
NH4 ref: -56.8542439306, quick: -56.854245606 diff: 1.675400000067384e-06
PH3 ref: -343.058460502, quick: -343.058482771 diff: 2.2268999998686922e-05
SiH4 ref: -291.435053152, quick: -291.435208628 diff: 0.0001554759999748967
SO2 ref: -548.311866835, quick: -548.311838296 diff: -2.853900002719456e-05
```

### CODE REVIEW

**Comment by Madu86** [comment]
For CaCl2 and HI there is a significant difference in energy at the HF/def2-svp level. These are the ref vs QUICK energies for the same molecules. Note that I have also added HI here. The difference is huge. 

```
AlH3 ref: -243.179088938, quick: -243.179088751 diff: -1.870000119197357e-07
BeH2 ref: -15.7062688439, quick: -15.706268694 diff: -1.4989999996828374e-07
BH3 ref: -26.3553080463, quick: -26.355308025 diff: -2.1299999986013063e-08
CaCl2 ref: -1590.60839685, quick: -1590.533430982 diff: -0.07496586799993565
CH4 ref: -40.1707755676, quick: -40.170775535 diff: -3.2600006250049773e-08
H2O ref: -75.9339901979, quick: -75.933990193 diff: -4.900002181784657e-09
HBr ref: -2572.59954509, quick: -2572.599545004 diff: -8.600000001024455e-08
HI ref: -296.992367764, quick: -2043.888505221 diff: 1746.8961374570001
KCl ref: -1058.49309689, quick: -1058.493096883 diff: -7.0001533458707854e-09
LiF ref: -106.833458069, quick: -106.833458073 diff: 4.000000330961484e-09
MgO ref: -274.203732663, quick: -274.203732652 diff: -1.0999997357430402e-08
NaCl ref: -621.228718865, quick: -621.228718859 diff: -6.000050234433729e-09
NH4 ref: -56.4941698583, quick: -56.494169828 diff: -3.03000007306764e-08
PH3 ref: -342.368022562, quick: -342.368022497 diff: -6.499999471998308e-08
SiH4 ref: -290.768579472, quick: -290.768579429 diff: -4.3000000005122274e-08
SO2 ref: -546.873340403, quick: -546.873340411 diff: 7.999915396794677e-09
```

**Comment by vwcruzeiro** [comment]
Any ideas why HI has such a huge difference?

**Comment by Madu86** [comment]
> Any ideas why HI has such a huge difference?

Screwed up initial guess. See issue #131. @Altaimorin is currently assigned to investigate this.

**Comment by vwcruzeiro** [comment]
Are we going to merge the current PR now or just after @Altaimorin is done?

**Comment by Madu86** [comment]
Lets merge this PR. @Altaimorin can fix issue #131 and submit a new PR.

**Comment by vwcruzeiro** [comment]
Please rebase it before we merge. Let's make sure the tests pass here. Thanks.

**Comment by Madu86** [comment]
@vwcruzeiro CI tests are done. Please go ahead with merging.

**Pull request merged**
