### PR TITLE
Updates to readme 

### PR DESCRIPTION
**Pull request by Madu86**
I have made some minor improvements to readme file and removed obsolete update.log. Please check and merge.

### CODE REVIEW

**Comment by agoetz** [comment]
@Madu86 please add limitations
- Cartesian basis functions, spherical harmonics not supported
- XC quadrature grid is fixed. Using SG1 grid.

**Comment by Madu86** [comment]
@agoetz Just added them.

**Review by agoetz — APPROVED** [review]
I added info on parallel implementations and citations for DFT, libxc, GPU ERIs.

**Comment by agoetz** [comment]
That's all I can think of. I am going to merge it now.

**Pull request merged**
